/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import javax.swing.JFrame;

/**
 *
 * @author Mi PC
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelRegistroUsuario = new javax.swing.JPanel();
        IconoUsuario = new javax.swing.JLabel();
        LabelRegistroUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CerrarVentana = new javax.swing.JLabel();
        TituloVentana = new javax.swing.JLabel();
        UsuarioField = new javax.swing.JTextField();
        LabelContraseña = new javax.swing.JLabel();
        CorreoElectronicoField = new javax.swing.JTextField();
        LabelCorreoElectronico = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LabelUsuario = new javax.swing.JLabel();
        BotonRegistrarse = new javax.swing.JButton();
        LabelIniciarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign up");
        setUndecorated(true);
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(null);

        PanelRegistroUsuario.setBackground(new java.awt.Color(0, 102, 204));

        IconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/User_No-.png"))); // NOI18N

        LabelRegistroUsuario.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LabelRegistroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelRegistroUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRegistroUsuario.setText("Registro de Usuario");

        javax.swing.GroupLayout PanelRegistroUsuarioLayout = new javax.swing.GroupLayout(PanelRegistroUsuario);
        PanelRegistroUsuario.setLayout(PanelRegistroUsuarioLayout);
        PanelRegistroUsuarioLayout.setHorizontalGroup(
            PanelRegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroUsuarioLayout.createSequentialGroup()
                        .addComponent(LabelRegistroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroUsuarioLayout.createSequentialGroup()
                        .addGap(0, 81, Short.MAX_VALUE)
                        .addComponent(IconoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        PanelRegistroUsuarioLayout.setVerticalGroup(
            PanelRegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroUsuarioLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(IconoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelRegistroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        PanelPrincipal.add(PanelRegistroUsuario);
        PanelRegistroUsuario.setBounds(0, 0, 314, 457);

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        CerrarVentana.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CerrarVentana.setForeground(new java.awt.Color(255, 255, 255));
        CerrarVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CerrarVentana.setText("x");
        CerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarVentanaMouseClicked(evt);
            }
        });
        CerrarVentana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CerrarVentanaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CerrarVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        PanelPrincipal.add(jPanel3);
        jPanel3.setBounds(586, 0, 31, 33);

        TituloVentana.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        TituloVentana.setForeground(new java.awt.Color(102, 102, 102));
        TituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloVentana.setText("Registrarse");
        PanelPrincipal.add(TituloVentana);
        TituloVentana.setBounds(350, 70, 230, 60);

        UsuarioField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        UsuarioField.setForeground(new java.awt.Color(51, 51, 51));
        UsuarioField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        UsuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioFieldActionPerformed(evt);
            }
        });
        PanelPrincipal.add(UsuarioField);
        UsuarioField.setBounds(350, 250, 240, 40);

        LabelContraseña.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LabelContraseña.setForeground(new java.awt.Color(51, 51, 51));
        LabelContraseña.setText("Contraseña");
        PanelPrincipal.add(LabelContraseña);
        LabelContraseña.setBounds(350, 310, 110, 16);

        CorreoElectronicoField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        CorreoElectronicoField.setForeground(new java.awt.Color(51, 51, 51));
        CorreoElectronicoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        PanelPrincipal.add(CorreoElectronicoField);
        CorreoElectronicoField.setBounds(350, 170, 240, 40);

        LabelCorreoElectronico.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LabelCorreoElectronico.setForeground(new java.awt.Color(51, 51, 51));
        LabelCorreoElectronico.setText("Correo Electronico");
        PanelPrincipal.add(LabelCorreoElectronico);
        LabelCorreoElectronico.setBounds(350, 150, 110, 16);

        PasswordField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(51, 51, 51));
        PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        PanelPrincipal.add(PasswordField);
        PasswordField.setBounds(350, 330, 240, 40);

        LabelUsuario.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(51, 51, 51));
        LabelUsuario.setText("Usuario");
        PanelPrincipal.add(LabelUsuario);
        LabelUsuario.setBounds(350, 230, 110, 16);

        BotonRegistrarse.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BotonRegistrarse.setText("Registrarse");
        BotonRegistrarse.setBorder(null);
        BotonRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelPrincipal.add(BotonRegistrarse);
        BotonRegistrarse.setBounds(430, 390, 90, 30);

        LabelIniciarSesion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        LabelIniciarSesion.setForeground(new java.awt.Color(0, 102, 204));
        LabelIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelIniciarSesion.setText("Tienes una cuenta? Inicia Sesion");
        LabelIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelIniciarSesionMouseClicked(evt);
            }
        });
        PanelPrincipal.add(LabelIniciarSesion);
        LabelIniciarSesion.setBounds(350, 430, 250, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(617, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void CerrarVentanaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CerrarVentanaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarVentanaKeyPressed

    private void CerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarVentanaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarVentanaMouseClicked

    private void LabelIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelIniciarSesionMouseClicked
        dispose();
        new InicioSesion().setVisible(true);
    }//GEN-LAST:event_LabelIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistrarse;
    private javax.swing.JLabel CerrarVentana;
    private javax.swing.JTextField CorreoElectronicoField;
    private javax.swing.JLabel IconoUsuario;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelCorreoElectronico;
    private javax.swing.JLabel LabelIniciarSesion;
    private javax.swing.JLabel LabelRegistroUsuario;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelRegistroUsuario;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel TituloVentana;
    private javax.swing.JTextField UsuarioField;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
