/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantallaFinal;

import PrincipalScreen.PantallaPrincipal;
import Ranking.Ranking;
import Tienda.Tienda;

/**
 *Clase que crea la ventana final del videojuego
 * @author CRISTIAN
 */
public class PantallaFinal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaFinal
     */
    private String player, image;
    private int money;
    public PantallaFinal(String name, String url, int monedas) {
        player = name;
        image = url;
        money = monedas;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Ranking = new javax.swing.JLabel();
        Tienda = new javax.swing.JLabel();
        RegresarInicio = new javax.swing.JLabel();
        GameOver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        Ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/scores.png"))); // NOI18N
        Ranking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ranking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RankingMouseClicked(evt);
            }
        });

        Tienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        Tienda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TiendaMouseClicked(evt);
            }
        });

        RegresarInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/return.png"))); // NOI18N
        RegresarInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegresarInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarInicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(Ranking, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(RegresarInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tienda)
                        .addComponent(RegresarInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Ranking, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        GameOver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PantallaFinal/GameOver.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GameOver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(GameOver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Abre la ventana del Ranking para mostrarle al usuario las mejores posiciones vpero sin cerrar la ventana final del juego
 * @param evt 
 */
    private void RankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RankingMouseClicked
       new Ranking().setVisible(true);
    }//GEN-LAST:event_RankingMouseClicked
/**
 * Cierra la ventana final y abre la ventana inicial del juego
 * @param evt 
 */
    private void RegresarInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarInicioMouseClicked
        dispose();
        PantallaPrincipal pp = new PantallaPrincipal(player);
        pp.setVisible(true);
    }//GEN-LAST:event_RegresarInicioMouseClicked
/**
 * Cierra la ventana del juego y abre la ventana de la tienda para que el usuario pueda realizar compras
 * @param evt 
 */
    private void TiendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TiendaMouseClicked
        dispose();
        Tienda t = new Tienda(player, image, money);
        t.setVisible(true);
    }//GEN-LAST:event_TiendaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameOver;
    private javax.swing.JLabel Ranking;
    private javax.swing.JLabel RegresarInicio;
    private javax.swing.JLabel Tienda;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
