/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ayuda;


/**
 * Esta clase es la ventana "Ayuda" que muestra los controles de juegp
 * @author CRISTIAN
 */
public class Ayuda extends javax.swing.JFrame {

    /**
     * Creates new form Ayuda
     */
    public Ayuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Izquierda = new javax.swing.JLabel();
        Derecha = new javax.swing.JLabel();
        Arriba = new javax.swing.JLabel();
        Abajo = new javax.swing.JLabel();
        Disparar = new javax.swing.JLabel();
        BotonOK = new javax.swing.JButton();
        icono = new javax.swing.JLabel();
        Pausa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        Titulo.setText("Ayuda");

        Izquierda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Izquierda.setText("Left Arrow-  mover izquierda");

        Derecha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Derecha.setText("Right Arrow - Mover derecha");

        Arriba.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Arriba.setText("Up Arrow - Mover Arriba");

        Abajo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Abajo.setText("Down Arrow - Moverse abajo");

        Disparar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Disparar.setText("Space - Disparar");

        BotonOK.setText("OK");
        BotonOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonOKMouseClicked(evt);
            }
        });

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/help.png"))); // NOI18N

        Pausa.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Pausa.setText("ESC - Pausa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Izquierda)
                    .addComponent(Derecha)
                    .addComponent(Abajo))
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(icono)
                                .addGap(53, 53, 53)
                                .addComponent(Titulo))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(Arriba))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pausa)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Disparar)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo)
                    .addComponent(icono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(Izquierda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Derecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Abajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arriba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Disparar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pausa)
                .addGap(28, 28, 28)
                .addComponent(BotonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Cierra la ventana.
     * @param evt 
     */
    private void BotonOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonOKMouseClicked
        dispose();
    }//GEN-LAST:event_BotonOKMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abajo;
    private javax.swing.JLabel Arriba;
    private javax.swing.JButton BotonOK;
    private javax.swing.JLabel Derecha;
    private javax.swing.JLabel Disparar;
    private javax.swing.JLabel Izquierda;
    private javax.swing.JLabel Pausa;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
